#### general settings
name: Dual-Window-SE
device: cuda:3

#### dataset settings
dataset:
  train:
    source: /data/home/wangqingzheng/Edinburgh-Dataset/noisy_trainset_wav
    target: /data/home/wangqingzheng/Edinburgh-Dataset/clean_trainset_wav

  test:
    source: /data/home/wangqingzheng/Edinburgh-Dataset/noisy_testset_wav
    target: /data/home/wangqingzheng/Edinburgh-Dataset/clean_testset_wav

  dataloader:
    shuffle: true

  audio16:
    window: tukey
    nfft: 256
    window_length: 256
    hop_length: 32
    center: False
    is_mag: True  # abs(tf-domain)

  audio4:
    nfft = 64
    window_length = 64
    hop_length = 32

#### network structures
DNN1:
  conv2d_cauln:
    oFM: 30
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 1
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  resblock:
    iFM: 30
    oFM: 30

    depth_conv1:
      kernel_size: !!python/tuple [ 3, 3 ]
      stride: !!python/tuple [ 1, 1 ]
      padding: !!python/tuple [ 1, 1 ]
      dilation: !!python/tuple [ 1, 1 ]
    point_conv1:
      kernel_size: !!python/tuple [ 1, 1 ]
      out_channels: 64

    depth_conv2:
      kernel_size: !!python/tuple [ 3, 3 ]
      stride: !!python/tuple [ 1, 1 ]
      padding: !!python/tuple [ 2, 1 ]
      dilation: !!python/tuple [ 2, 1 ]
    point_conv2:
      kernel_size: !!python/tuple [ 1, 1 ]

    depth_conv3:
      kernel_size: !!python/tuple [ 3, 3 ]
      stride: !!python/tuple [ 1, 1 ]
      padding: !!python/tuple [ 4, 1 ]
      dilation: !!python/tuple [ 4, 1 ]
    point_conv3:
      kernel_size: !!python/tuple [ 1, 1 ]

    depth_conv4:
      kernel_size: !!python/tuple [ 3, 3 ]
      stride: !!python/tuple [ 1, 1 ]
      padding: !!python/tuple [ 8, 1 ]
      dilation: !!python/tuple [ 8, 1 ]
    point_conv4:
      kernel_size: !!python/tuple [ 1, 1 ]

    depth_conv5:
      kernel_size: !!python/tuple [ 3, 3 ]
      stride: !!python/tuple [ 1, 1 ]
      padding: !!python/tuple [ 16, 1 ]
      dilation: !!python/tuple [ 16, 1 ]
    point_conv5:
      kernel_size: !!python/tuple [ 1, 1 ]

  conv2d_prelu_bn30:
    iFM: 30
    oFM: 30
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 2
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  conv2d_prelu_bn64:
    iFM: 30
    oFM: 64
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 2
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  conv2d_prelu_bn192:
    iFM: 64
    oFM: 192
    T: 100
    F: 80
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 1
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  deconv2d_prelu_bn6430:
    iFM: 64
    oFM: 30
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 2
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  deconv2d_prelu_bn30:
    iFM: 30
    oFM: 30
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 2
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  deconv2d_prelu_bn64:
    iFM: 192
    oFM: 64
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 1
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  skip_connection30:
    iFM: 30
    oFM: 30
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 1
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  skip_connection64:
    iFM: 64
    oFM: 64
    kernel_time: 1
    kernel_freq: 1
    stride_time: 1
    stride_freq: 1
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  skip_connection192:
    iFM: 192
    oFM: 192
    kernel_time: 1
    kernel_freq: 1
    stride_time: 1
    stride_freq: 1
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  deconv2d:
    iFM: 30
    kernel_time: 1
    kernel_freq: 3
    stride_time: 1
    stride_freq: 1
    pad_time: 0
    pad_freq: 0
    dilation_time: 1
    dilation_freq: 1

  lstm:
    hidden_size: 300
    num_layers: 3
    batch_first: true


#### training settings: learning rate scheme, loss
train:
  batch_size: 64
  epoch: 100
  early_stop: 10
  path: /data/home/wangqingzheng/data/home/wangqingzheng/Dual-Window-SE/checkpoints
  is_gpu: true

#### Optimizer settings
optim:
  name: Adam   ### Adam, RMSprop, SGD
  lr: 1.0e-5
  momentum: 0.9
  weight_decay: 0
  clip_norm: 200 # 梯度减切Gradient Clip。
  # 设置一个梯度减切的阈值，如果在更新梯度的时候，
  # 梯度超过这个阈值，则会将其限制在这个范围之内，防止梯度爆炸。

#### Resume training settings
resume:
  state: false
  path: /data/home/wangqingzheng/data/home/wangqingzheng/Dual-Window-SE/checkpoints

#### logger
logger:
  name: DPCL
  path: /data/home/wangqingzheng/data/home/wangqingzheng/Dual-Window-SE/checkpoints
  screen: true
  tofile: false
  print_freq: 100